# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:8

before_script:
  # To prevent TypeError: log.gauge.isEnabled is not a function
  # See: https://github.com/npm/npmlog/issues/48
  - rm -rf node_modules/npm
  - yarn

cache:
  paths:
    - node_modules/

lint:
  script:
    - npm run --silent lint

tests:
  script:
   - npm run test -- -b  PhantomJS
