# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:12

before_script:
  - yarn || echo "yarn not found, this is expected if we are on the deploy steps"

cache:
  paths:
    - node_modules/

stages:
  - checks
  - build
  - deploy

lint:
  stage: checks
  script:
    - yarn run --silent lint
  except:
    - triggers

tests:
  stage: checks
  script:
    - ./node_modules/.bin/nps test.coverage
  except:
    - triggers

build:
  stage: build
  variables:
    ENV: staging
    API_VERSION: latest
    VERSION: $CI_COMMIT_REF_SLUG
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  script:
    - ./node_modules/.bin/nps "build.config --env $ENV --version $VERSION --api-version $API_VERSION" "webpack.build --env.environment=$ENV" "build.manifest --env $ENV --version $VERSION"
  except:
    - tags

deploy in staging:
  stage: deploy
  image: registry.gitlab.com/arenaoftitans/aot-infra:latest
  environment:
    name: staging
    url: https://dev.last-run.com/index-$CI_COMMIT_REF_SLUG.html
  script:
    - git clone https://gitlab.com/arenaoftitans/aot-infra.git /opt/aot-infra
    - cd /opt/aot-infra
    - mv /builds/arenaoftitans/arena-of-titans ./front
    - ansible-playbook -i environments/staging front.yml -e version=$CI_COMMIT_REF_SLUG
    - echo "Deployed to https://dev.last-run.com/index-$CI_COMMIT_REF_SLUG.html"
  when: manual
  except:
    - tags
    - triggers
