# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10

before_script:
  # To prevent TypeError: log.gauge.isEnabled is not a function
  # See: https://github.com/npm/npmlog/issues/48
  - rm -rf node_modules/npm
  - yarn || echo "yarn not found, this is expected if we are on the deploy steps"

cache:
  paths:
    - node_modules/

stages:
  - checks
  - build
  - deploy

lint:
  stage: checks
  script:
    - npm run --silent lint
  except:
    - triggers

tests:
  stage: checks
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y firefox-esr
    - firefox --version
  script:
  # We don't use chromium too because it is a bit harder to setup and won't bring much value here.
   - npm run test -- -b FirefoxHeadless
  except:
    - triggers

build:
  stage: build
  variables:
    ENV: staging
    API_VERSION: latest
    VERSION: $CI_COMMIT_REF_SLUG
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  script:
    - npm run build -- --env $ENV --version $VERSION
  except:
    - tags

deploy in staging:
  stage: deploy
  image: registry.gitlab.com/arenaoftitans/aot-infra:latest
  environment:
    name: staging
    url: https://dev.arenaoftitans.com/index-$CI_COMMIT_REF_SLUG.html
  script:
    - git clone https://gitlab.com/arenaoftitans/aot-infra.git /opt/aot-infra
    - cd /opt/aot-infra
    - VERSION=$CI_COMMIT_REF_SLUG STAGE=staging ./dk-run.sh deployfront
    - echo "Deployed to https://dev.arenaoftitans.com/index-$CI_COMMIT_REF_SLUG.html"
  when: manual
  except:
    - tags
    - triggers
