image: node:latest

pipelines:
  default:
    - step:
        script:
          - yarn
          - npm run --silent lint
          - cp config/test-cfg.js app/services/configuration.js
          - npm run test -- -b PhantomJS
