System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system",
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "aurelia": [
      "github:jspm/nodelibs-process@0.1.2",
      "github:jspm/nodelibs-process@0.1.2/index",
      "npm:aurelia-binding@1.0.0-beta.1.1.1",
      "npm:aurelia-binding@1.0.0-beta.1.1.1/aurelia-binding",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.1.1",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.1.1/aurelia-bootstrapper",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.2",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.2/aurelia-dependency-injection",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.1.0",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.1.0/aurelia-event-aggregator",
      "npm:aurelia-framework@1.0.0-beta.1.1.1",
      "npm:aurelia-framework@1.0.0-beta.1.1.1/aurelia-framework",
      "npm:aurelia-history-browser@1.0.0-beta.1.1.1",
      "npm:aurelia-history-browser@1.0.0-beta.1.1.1/aurelia-history-browser",
      "npm:aurelia-history@1.0.0-beta.1.1.1",
      "npm:aurelia-history@1.0.0-beta.1.1.1/aurelia-history",
      "npm:aurelia-loader-default@1.0.0-beta.1.1.1",
      "npm:aurelia-loader-default@1.0.0-beta.1.1.1/aurelia-loader-default",
      "npm:aurelia-loader@1.0.0-beta.1.1.0",
      "npm:aurelia-loader@1.0.0-beta.1.1.0/aurelia-loader",
      "npm:aurelia-logging-console@1.0.0-beta.1.1.3",
      "npm:aurelia-logging-console@1.0.0-beta.1.1.3/aurelia-logging-console",
      "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "npm:aurelia-logging@1.0.0-beta.1.1.1/aurelia-logging",
      "npm:aurelia-metadata@1.0.0-beta.1.1.3",
      "npm:aurelia-metadata@1.0.0-beta.1.1.3/aurelia-metadata",
      "npm:aurelia-pal-browser@1.0.0-beta.1.1.2",
      "npm:aurelia-pal-browser@1.0.0-beta.1.1.2/aurelia-pal-browser",
      "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "npm:aurelia-pal@1.0.0-beta.1.1.1/aurelia-pal",
      "npm:aurelia-path@1.0.0-beta.1.1.0",
      "npm:aurelia-path@1.0.0-beta.1.1.0/aurelia-path",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.1.0",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.1.0/aurelia-route-recognizer",
      "npm:aurelia-router@1.0.0-beta.1.1.0",
      "npm:aurelia-router@1.0.0-beta.1.1.0/aurelia-router",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.0",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.0/aurelia-task-queue",
      "npm:aurelia-templating-binding@1.0.0-beta.1.1.0",
      "npm:aurelia-templating-binding@1.0.0-beta.1.1.0/aurelia-templating-binding",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/analyze-view-factory",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/array-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/aurelia-templating-resources",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/binding-mode-behaviors",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/binding-signaler",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/compile-spy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/compose",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/css-resource",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/debounce-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/dynamic-element",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/focus",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/html-sanitizer",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/if",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/map-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/null-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/number-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/repeat",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/repeat-strategy-locator",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/repeat-utilities",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/replaceable",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/sanitize-html",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/set-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/show",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/signal-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/throttle-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/update-trigger-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/view-spy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/with",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.0",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.0/aurelia-templating-router",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.0/route-href",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.0/route-loader",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.0/router-view",
      "npm:aurelia-templating@1.0.0-beta.1.1.0",
      "npm:aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating",
      "npm:core-js@2.0.3",
      "npm:core-js@2.0.3/index",
      "npm:core-js@2.0.3/modules/_",
      "npm:core-js@2.0.3/modules/_a-function",
      "npm:core-js@2.0.3/modules/_add-to-unscopables",
      "npm:core-js@2.0.3/modules/_an-instance",
      "npm:core-js@2.0.3/modules/_an-object",
      "npm:core-js@2.0.3/modules/_array-copy-within",
      "npm:core-js@2.0.3/modules/_array-fill",
      "npm:core-js@2.0.3/modules/_array-from-iterable",
      "npm:core-js@2.0.3/modules/_array-includes",
      "npm:core-js@2.0.3/modules/_array-methods",
      "npm:core-js@2.0.3/modules/_array-species-create",
      "npm:core-js@2.0.3/modules/_bind",
      "npm:core-js@2.0.3/modules/_classof",
      "npm:core-js@2.0.3/modules/_cof",
      "npm:core-js@2.0.3/modules/_collection",
      "npm:core-js@2.0.3/modules/_collection-strong",
      "npm:core-js@2.0.3/modules/_collection-to-json",
      "npm:core-js@2.0.3/modules/_collection-weak",
      "npm:core-js@2.0.3/modules/_core",
      "npm:core-js@2.0.3/modules/_ctx",
      "npm:core-js@2.0.3/modules/_defined",
      "npm:core-js@2.0.3/modules/_descriptors",
      "npm:core-js@2.0.3/modules/_dom-create",
      "npm:core-js@2.0.3/modules/_enum-keys",
      "npm:core-js@2.0.3/modules/_export",
      "npm:core-js@2.0.3/modules/_fails",
      "npm:core-js@2.0.3/modules/_fails-is-regexp",
      "npm:core-js@2.0.3/modules/_fix-re-wks",
      "npm:core-js@2.0.3/modules/_flags",
      "npm:core-js@2.0.3/modules/_for-of",
      "npm:core-js@2.0.3/modules/_get-names",
      "npm:core-js@2.0.3/modules/_global",
      "npm:core-js@2.0.3/modules/_has",
      "npm:core-js@2.0.3/modules/_hide",
      "npm:core-js@2.0.3/modules/_html",
      "npm:core-js@2.0.3/modules/_invoke",
      "npm:core-js@2.0.3/modules/_iobject",
      "npm:core-js@2.0.3/modules/_is-array",
      "npm:core-js@2.0.3/modules/_is-array-iter",
      "npm:core-js@2.0.3/modules/_is-integer",
      "npm:core-js@2.0.3/modules/_is-object",
      "npm:core-js@2.0.3/modules/_is-regexp",
      "npm:core-js@2.0.3/modules/_iter-call",
      "npm:core-js@2.0.3/modules/_iter-create",
      "npm:core-js@2.0.3/modules/_iter-define",
      "npm:core-js@2.0.3/modules/_iter-detect",
      "npm:core-js@2.0.3/modules/_iter-step",
      "npm:core-js@2.0.3/modules/_iterators",
      "npm:core-js@2.0.3/modules/_keyof",
      "npm:core-js@2.0.3/modules/_library",
      "npm:core-js@2.0.3/modules/_math-expm1",
      "npm:core-js@2.0.3/modules/_math-log1p",
      "npm:core-js@2.0.3/modules/_math-sign",
      "npm:core-js@2.0.3/modules/_meta",
      "npm:core-js@2.0.3/modules/_microtask",
      "npm:core-js@2.0.3/modules/_object-assign",
      "npm:core-js@2.0.3/modules/_object-define",
      "npm:core-js@2.0.3/modules/_object-sap",
      "npm:core-js@2.0.3/modules/_object-to-array",
      "npm:core-js@2.0.3/modules/_own-keys",
      "npm:core-js@2.0.3/modules/_partial",
      "npm:core-js@2.0.3/modules/_path",
      "npm:core-js@2.0.3/modules/_property-desc",
      "npm:core-js@2.0.3/modules/_redefine",
      "npm:core-js@2.0.3/modules/_redefine-all",
      "npm:core-js@2.0.3/modules/_replacer",
      "npm:core-js@2.0.3/modules/_same-value",
      "npm:core-js@2.0.3/modules/_set-proto",
      "npm:core-js@2.0.3/modules/_set-species",
      "npm:core-js@2.0.3/modules/_set-to-string-tag",
      "npm:core-js@2.0.3/modules/_shared",
      "npm:core-js@2.0.3/modules/_species-constructor",
      "npm:core-js@2.0.3/modules/_string-at",
      "npm:core-js@2.0.3/modules/_string-context",
      "npm:core-js@2.0.3/modules/_string-html",
      "npm:core-js@2.0.3/modules/_string-pad",
      "npm:core-js@2.0.3/modules/_string-repeat",
      "npm:core-js@2.0.3/modules/_string-trim",
      "npm:core-js@2.0.3/modules/_task",
      "npm:core-js@2.0.3/modules/_to-index",
      "npm:core-js@2.0.3/modules/_to-integer",
      "npm:core-js@2.0.3/modules/_to-iobject",
      "npm:core-js@2.0.3/modules/_to-length",
      "npm:core-js@2.0.3/modules/_to-object",
      "npm:core-js@2.0.3/modules/_to-primitive",
      "npm:core-js@2.0.3/modules/_typed",
      "npm:core-js@2.0.3/modules/_typed-array",
      "npm:core-js@2.0.3/modules/_typed-buffer",
      "npm:core-js@2.0.3/modules/_uid",
      "npm:core-js@2.0.3/modules/_wks",
      "npm:core-js@2.0.3/modules/core.delay",
      "npm:core-js@2.0.3/modules/core.dict",
      "npm:core-js@2.0.3/modules/core.function.part",
      "npm:core-js@2.0.3/modules/core.get-iterator",
      "npm:core-js@2.0.3/modules/core.get-iterator-method",
      "npm:core-js@2.0.3/modules/core.is-iterable",
      "npm:core-js@2.0.3/modules/core.number.iterator",
      "npm:core-js@2.0.3/modules/core.object.classof",
      "npm:core-js@2.0.3/modules/core.object.define",
      "npm:core-js@2.0.3/modules/core.object.is-object",
      "npm:core-js@2.0.3/modules/core.object.make",
      "npm:core-js@2.0.3/modules/core.regexp.escape",
      "npm:core-js@2.0.3/modules/core.string.escape-html",
      "npm:core-js@2.0.3/modules/core.string.unescape-html",
      "npm:core-js@2.0.3/modules/es5",
      "npm:core-js@2.0.3/modules/es6.array.copy-within",
      "npm:core-js@2.0.3/modules/es6.array.fill",
      "npm:core-js@2.0.3/modules/es6.array.find",
      "npm:core-js@2.0.3/modules/es6.array.find-index",
      "npm:core-js@2.0.3/modules/es6.array.from",
      "npm:core-js@2.0.3/modules/es6.array.iterator",
      "npm:core-js@2.0.3/modules/es6.array.of",
      "npm:core-js@2.0.3/modules/es6.array.species",
      "npm:core-js@2.0.3/modules/es6.date.to-string",
      "npm:core-js@2.0.3/modules/es6.function.has-instance",
      "npm:core-js@2.0.3/modules/es6.function.name",
      "npm:core-js@2.0.3/modules/es6.map",
      "npm:core-js@2.0.3/modules/es6.math.acosh",
      "npm:core-js@2.0.3/modules/es6.math.asinh",
      "npm:core-js@2.0.3/modules/es6.math.atanh",
      "npm:core-js@2.0.3/modules/es6.math.cbrt",
      "npm:core-js@2.0.3/modules/es6.math.clz32",
      "npm:core-js@2.0.3/modules/es6.math.cosh",
      "npm:core-js@2.0.3/modules/es6.math.expm1",
      "npm:core-js@2.0.3/modules/es6.math.fround",
      "npm:core-js@2.0.3/modules/es6.math.hypot",
      "npm:core-js@2.0.3/modules/es6.math.imul",
      "npm:core-js@2.0.3/modules/es6.math.log10",
      "npm:core-js@2.0.3/modules/es6.math.log1p",
      "npm:core-js@2.0.3/modules/es6.math.log2",
      "npm:core-js@2.0.3/modules/es6.math.sign",
      "npm:core-js@2.0.3/modules/es6.math.sinh",
      "npm:core-js@2.0.3/modules/es6.math.tanh",
      "npm:core-js@2.0.3/modules/es6.math.trunc",
      "npm:core-js@2.0.3/modules/es6.number.constructor",
      "npm:core-js@2.0.3/modules/es6.number.epsilon",
      "npm:core-js@2.0.3/modules/es6.number.is-finite",
      "npm:core-js@2.0.3/modules/es6.number.is-integer",
      "npm:core-js@2.0.3/modules/es6.number.is-nan",
      "npm:core-js@2.0.3/modules/es6.number.is-safe-integer",
      "npm:core-js@2.0.3/modules/es6.number.max-safe-integer",
      "npm:core-js@2.0.3/modules/es6.number.min-safe-integer",
      "npm:core-js@2.0.3/modules/es6.number.parse-float",
      "npm:core-js@2.0.3/modules/es6.number.parse-int",
      "npm:core-js@2.0.3/modules/es6.object.assign",
      "npm:core-js@2.0.3/modules/es6.object.freeze",
      "npm:core-js@2.0.3/modules/es6.object.get-own-property-descriptor",
      "npm:core-js@2.0.3/modules/es6.object.get-own-property-names",
      "npm:core-js@2.0.3/modules/es6.object.get-prototype-of",
      "npm:core-js@2.0.3/modules/es6.object.is",
      "npm:core-js@2.0.3/modules/es6.object.is-extensible",
      "npm:core-js@2.0.3/modules/es6.object.is-frozen",
      "npm:core-js@2.0.3/modules/es6.object.is-sealed",
      "npm:core-js@2.0.3/modules/es6.object.keys",
      "npm:core-js@2.0.3/modules/es6.object.prevent-extensions",
      "npm:core-js@2.0.3/modules/es6.object.seal",
      "npm:core-js@2.0.3/modules/es6.object.set-prototype-of",
      "npm:core-js@2.0.3/modules/es6.object.to-string",
      "npm:core-js@2.0.3/modules/es6.promise",
      "npm:core-js@2.0.3/modules/es6.reflect.apply",
      "npm:core-js@2.0.3/modules/es6.reflect.construct",
      "npm:core-js@2.0.3/modules/es6.reflect.define-property",
      "npm:core-js@2.0.3/modules/es6.reflect.delete-property",
      "npm:core-js@2.0.3/modules/es6.reflect.enumerate",
      "npm:core-js@2.0.3/modules/es6.reflect.get",
      "npm:core-js@2.0.3/modules/es6.reflect.get-own-property-descriptor",
      "npm:core-js@2.0.3/modules/es6.reflect.get-prototype-of",
      "npm:core-js@2.0.3/modules/es6.reflect.has",
      "npm:core-js@2.0.3/modules/es6.reflect.is-extensible",
      "npm:core-js@2.0.3/modules/es6.reflect.own-keys",
      "npm:core-js@2.0.3/modules/es6.reflect.prevent-extensions",
      "npm:core-js@2.0.3/modules/es6.reflect.set",
      "npm:core-js@2.0.3/modules/es6.reflect.set-prototype-of",
      "npm:core-js@2.0.3/modules/es6.regexp.constructor",
      "npm:core-js@2.0.3/modules/es6.regexp.flags",
      "npm:core-js@2.0.3/modules/es6.regexp.match",
      "npm:core-js@2.0.3/modules/es6.regexp.replace",
      "npm:core-js@2.0.3/modules/es6.regexp.search",
      "npm:core-js@2.0.3/modules/es6.regexp.split",
      "npm:core-js@2.0.3/modules/es6.set",
      "npm:core-js@2.0.3/modules/es6.string.anchor",
      "npm:core-js@2.0.3/modules/es6.string.big",
      "npm:core-js@2.0.3/modules/es6.string.blink",
      "npm:core-js@2.0.3/modules/es6.string.bold",
      "npm:core-js@2.0.3/modules/es6.string.code-point-at",
      "npm:core-js@2.0.3/modules/es6.string.ends-with",
      "npm:core-js@2.0.3/modules/es6.string.fixed",
      "npm:core-js@2.0.3/modules/es6.string.fontcolor",
      "npm:core-js@2.0.3/modules/es6.string.fontsize",
      "npm:core-js@2.0.3/modules/es6.string.from-code-point",
      "npm:core-js@2.0.3/modules/es6.string.includes",
      "npm:core-js@2.0.3/modules/es6.string.italics",
      "npm:core-js@2.0.3/modules/es6.string.iterator",
      "npm:core-js@2.0.3/modules/es6.string.link",
      "npm:core-js@2.0.3/modules/es6.string.raw",
      "npm:core-js@2.0.3/modules/es6.string.repeat",
      "npm:core-js@2.0.3/modules/es6.string.small",
      "npm:core-js@2.0.3/modules/es6.string.starts-with",
      "npm:core-js@2.0.3/modules/es6.string.strike",
      "npm:core-js@2.0.3/modules/es6.string.sub",
      "npm:core-js@2.0.3/modules/es6.string.sup",
      "npm:core-js@2.0.3/modules/es6.string.trim",
      "npm:core-js@2.0.3/modules/es6.symbol",
      "npm:core-js@2.0.3/modules/es6.typed.array-buffer",
      "npm:core-js@2.0.3/modules/es6.typed.data-view",
      "npm:core-js@2.0.3/modules/es6.typed.float32-array",
      "npm:core-js@2.0.3/modules/es6.typed.float64-array",
      "npm:core-js@2.0.3/modules/es6.typed.int16-array",
      "npm:core-js@2.0.3/modules/es6.typed.int32-array",
      "npm:core-js@2.0.3/modules/es6.typed.int8-array",
      "npm:core-js@2.0.3/modules/es6.typed.uint16-array",
      "npm:core-js@2.0.3/modules/es6.typed.uint32-array",
      "npm:core-js@2.0.3/modules/es6.typed.uint8-array",
      "npm:core-js@2.0.3/modules/es6.typed.uint8-clamped-array",
      "npm:core-js@2.0.3/modules/es6.weak-map",
      "npm:core-js@2.0.3/modules/es6.weak-set",
      "npm:core-js@2.0.3/modules/es7.array.includes",
      "npm:core-js@2.0.3/modules/es7.error.is-error",
      "npm:core-js@2.0.3/modules/es7.map.to-json",
      "npm:core-js@2.0.3/modules/es7.math.iaddh",
      "npm:core-js@2.0.3/modules/es7.math.imulh",
      "npm:core-js@2.0.3/modules/es7.math.isubh",
      "npm:core-js@2.0.3/modules/es7.math.umulh",
      "npm:core-js@2.0.3/modules/es7.object.entries",
      "npm:core-js@2.0.3/modules/es7.object.get-own-property-descriptors",
      "npm:core-js@2.0.3/modules/es7.object.values",
      "npm:core-js@2.0.3/modules/es7.set.to-json",
      "npm:core-js@2.0.3/modules/es7.string.at",
      "npm:core-js@2.0.3/modules/es7.string.pad-end",
      "npm:core-js@2.0.3/modules/es7.string.pad-start",
      "npm:core-js@2.0.3/modules/es7.string.trim-left",
      "npm:core-js@2.0.3/modules/es7.string.trim-right",
      "npm:core-js@2.0.3/modules/es7.system.global",
      "npm:core-js@2.0.3/modules/web.dom.iterable",
      "npm:core-js@2.0.3/modules/web.immediate",
      "npm:core-js@2.0.3/modules/web.timers",
      "npm:core-js@2.0.3/shim",
      "npm:process@0.11.2",
      "npm:process@0.11.2/browser",
      "npm:systemjs-plugin-json@0.1.0",
      "npm:systemjs-plugin-json@0.1.0/json"
    ],
    "aurelia.js": [
      "github:i18next/i18next@1.11.2.js",
      "github:i18next/i18next@1.11.2/i18next.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:aurelia-binding@1.0.0-beta.1.1.3.js",
      "npm:aurelia-binding@1.0.0-beta.1.1.3/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.1.2.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.1.2/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3/aurelia-dependency-injection.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1/aurelia-event-aggregator.js",
      "npm:aurelia-framework@1.0.0-beta.1.1.2.js",
      "npm:aurelia-framework@1.0.0-beta.1.1.2/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.1.2.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.1.2/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0-beta.1.1.1.js",
      "npm:aurelia-history@1.0.0-beta.1.1.1/aurelia-history.js",
      "npm:aurelia-i18n@0.4.10.js",
      "npm:aurelia-i18n@0.4.10/aurelia-i18n.js",
      "npm:aurelia-i18n@0.4.10/base-i18n.js",
      "npm:aurelia-i18n@0.4.10/defaultTranslations/relative.time.js",
      "npm:aurelia-i18n@0.4.10/df.js",
      "npm:aurelia-i18n@0.4.10/i18n.js",
      "npm:aurelia-i18n@0.4.10/nf.js",
      "npm:aurelia-i18n@0.4.10/relativeTime.js",
      "npm:aurelia-i18n@0.4.10/rt.js",
      "npm:aurelia-i18n@0.4.10/t.js",
      "npm:aurelia-i18n@0.4.10/utils.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.1.2.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.1.2/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0-beta.1.1.1.js",
      "npm:aurelia-loader@1.0.0-beta.1.1.1/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.1.4.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.1.4/aurelia-logging-console.js",
      "npm:aurelia-logging@1.0.0-beta.1.1.1.js",
      "npm:aurelia-logging@1.0.0-beta.1.1.1/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.0-beta.1.1.4.js",
      "npm:aurelia-metadata@1.0.0-beta.1.1.4/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.1.3.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.1.3/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.0.0-beta.1.1.1.js",
      "npm:aurelia-pal@1.0.0-beta.1.1.1/aurelia-pal.js",
      "npm:aurelia-path@1.0.0-beta.1.1.0.js",
      "npm:aurelia-path@1.0.0-beta.1.1.0/aurelia-path.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.1.1.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.1.1/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.0.0-beta.1.1.1.js",
      "npm:aurelia-router@1.0.0-beta.1.1.1/aurelia-router.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.1.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.1/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.1.1.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.1.1/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/binding-signaler.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/compile-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/compose.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/css-resource.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/dynamic-element.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/focus.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/if.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/repeat.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/replaceable.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/sanitize-html.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/show.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/view-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.1/with.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.1.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.1/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.1/route-href.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.1/route-loader.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.1/router-view.js",
      "npm:aurelia-templating@1.0.0-beta.1.1.1.js",
      "npm:aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js",
      "npm:core-js@2.1.0.js",
      "npm:core-js@2.1.0/index.js",
      "npm:core-js@2.1.0/modules/_a-function.js",
      "npm:core-js@2.1.0/modules/_a-number-value.js",
      "npm:core-js@2.1.0/modules/_add-to-unscopables.js",
      "npm:core-js@2.1.0/modules/_an-instance.js",
      "npm:core-js@2.1.0/modules/_an-object.js",
      "npm:core-js@2.1.0/modules/_array-copy-within.js",
      "npm:core-js@2.1.0/modules/_array-fill.js",
      "npm:core-js@2.1.0/modules/_array-from-iterable.js",
      "npm:core-js@2.1.0/modules/_array-includes.js",
      "npm:core-js@2.1.0/modules/_array-methods.js",
      "npm:core-js@2.1.0/modules/_array-reduce.js",
      "npm:core-js@2.1.0/modules/_array-species-create.js",
      "npm:core-js@2.1.0/modules/_bind.js",
      "npm:core-js@2.1.0/modules/_classof.js",
      "npm:core-js@2.1.0/modules/_cof.js",
      "npm:core-js@2.1.0/modules/_collection-strong.js",
      "npm:core-js@2.1.0/modules/_collection-to-json.js",
      "npm:core-js@2.1.0/modules/_collection-weak.js",
      "npm:core-js@2.1.0/modules/_collection.js",
      "npm:core-js@2.1.0/modules/_core.js",
      "npm:core-js@2.1.0/modules/_ctx.js",
      "npm:core-js@2.1.0/modules/_defined.js",
      "npm:core-js@2.1.0/modules/_descriptors.js",
      "npm:core-js@2.1.0/modules/_dom-create.js",
      "npm:core-js@2.1.0/modules/_enum-bug-keys.js",
      "npm:core-js@2.1.0/modules/_enum-keys.js",
      "npm:core-js@2.1.0/modules/_export.js",
      "npm:core-js@2.1.0/modules/_fails-is-regexp.js",
      "npm:core-js@2.1.0/modules/_fails.js",
      "npm:core-js@2.1.0/modules/_fix-re-wks.js",
      "npm:core-js@2.1.0/modules/_flags.js",
      "npm:core-js@2.1.0/modules/_for-of.js",
      "npm:core-js@2.1.0/modules/_global.js",
      "npm:core-js@2.1.0/modules/_has.js",
      "npm:core-js@2.1.0/modules/_hide.js",
      "npm:core-js@2.1.0/modules/_html.js",
      "npm:core-js@2.1.0/modules/_ie8-dom-define.js",
      "npm:core-js@2.1.0/modules/_inherit-if-required.js",
      "npm:core-js@2.1.0/modules/_invoke.js",
      "npm:core-js@2.1.0/modules/_iobject.js",
      "npm:core-js@2.1.0/modules/_is-array-iter.js",
      "npm:core-js@2.1.0/modules/_is-array.js",
      "npm:core-js@2.1.0/modules/_is-integer.js",
      "npm:core-js@2.1.0/modules/_is-object.js",
      "npm:core-js@2.1.0/modules/_is-regexp.js",
      "npm:core-js@2.1.0/modules/_iter-call.js",
      "npm:core-js@2.1.0/modules/_iter-create.js",
      "npm:core-js@2.1.0/modules/_iter-define.js",
      "npm:core-js@2.1.0/modules/_iter-detect.js",
      "npm:core-js@2.1.0/modules/_iter-step.js",
      "npm:core-js@2.1.0/modules/_iterators.js",
      "npm:core-js@2.1.0/modules/_keyof.js",
      "npm:core-js@2.1.0/modules/_library.js",
      "npm:core-js@2.1.0/modules/_math-expm1.js",
      "npm:core-js@2.1.0/modules/_math-log1p.js",
      "npm:core-js@2.1.0/modules/_math-sign.js",
      "npm:core-js@2.1.0/modules/_meta.js",
      "npm:core-js@2.1.0/modules/_metadata.js",
      "npm:core-js@2.1.0/modules/_microtask.js",
      "npm:core-js@2.1.0/modules/_object-assign.js",
      "npm:core-js@2.1.0/modules/_object-create.js",
      "npm:core-js@2.1.0/modules/_object-define.js",
      "npm:core-js@2.1.0/modules/_object-dp.js",
      "npm:core-js@2.1.0/modules/_object-dps.js",
      "npm:core-js@2.1.0/modules/_object-gopd.js",
      "npm:core-js@2.1.0/modules/_object-gopn-ext.js",
      "npm:core-js@2.1.0/modules/_object-gopn.js",
      "npm:core-js@2.1.0/modules/_object-gops.js",
      "npm:core-js@2.1.0/modules/_object-gpo.js",
      "npm:core-js@2.1.0/modules/_object-keys-internal.js",
      "npm:core-js@2.1.0/modules/_object-keys.js",
      "npm:core-js@2.1.0/modules/_object-pie.js",
      "npm:core-js@2.1.0/modules/_object-sap.js",
      "npm:core-js@2.1.0/modules/_object-to-array.js",
      "npm:core-js@2.1.0/modules/_own-keys.js",
      "npm:core-js@2.1.0/modules/_parse-float.js",
      "npm:core-js@2.1.0/modules/_parse-int.js",
      "npm:core-js@2.1.0/modules/_partial.js",
      "npm:core-js@2.1.0/modules/_path.js",
      "npm:core-js@2.1.0/modules/_property-desc.js",
      "npm:core-js@2.1.0/modules/_redefine-all.js",
      "npm:core-js@2.1.0/modules/_redefine.js",
      "npm:core-js@2.1.0/modules/_replacer.js",
      "npm:core-js@2.1.0/modules/_same-value.js",
      "npm:core-js@2.1.0/modules/_set-proto.js",
      "npm:core-js@2.1.0/modules/_set-species.js",
      "npm:core-js@2.1.0/modules/_set-to-string-tag.js",
      "npm:core-js@2.1.0/modules/_shared-key.js",
      "npm:core-js@2.1.0/modules/_shared.js",
      "npm:core-js@2.1.0/modules/_species-constructor.js",
      "npm:core-js@2.1.0/modules/_strict-method.js",
      "npm:core-js@2.1.0/modules/_string-at.js",
      "npm:core-js@2.1.0/modules/_string-context.js",
      "npm:core-js@2.1.0/modules/_string-html.js",
      "npm:core-js@2.1.0/modules/_string-pad.js",
      "npm:core-js@2.1.0/modules/_string-repeat.js",
      "npm:core-js@2.1.0/modules/_string-trim.js",
      "npm:core-js@2.1.0/modules/_string-ws.js",
      "npm:core-js@2.1.0/modules/_task.js",
      "npm:core-js@2.1.0/modules/_to-index.js",
      "npm:core-js@2.1.0/modules/_to-integer.js",
      "npm:core-js@2.1.0/modules/_to-iobject.js",
      "npm:core-js@2.1.0/modules/_to-length.js",
      "npm:core-js@2.1.0/modules/_to-object.js",
      "npm:core-js@2.1.0/modules/_to-primitive.js",
      "npm:core-js@2.1.0/modules/_typed-array.js",
      "npm:core-js@2.1.0/modules/_typed-buffer.js",
      "npm:core-js@2.1.0/modules/_typed.js",
      "npm:core-js@2.1.0/modules/_uid.js",
      "npm:core-js@2.1.0/modules/_wks.js",
      "npm:core-js@2.1.0/modules/core.delay.js",
      "npm:core-js@2.1.0/modules/core.dict.js",
      "npm:core-js@2.1.0/modules/core.function.part.js",
      "npm:core-js@2.1.0/modules/core.get-iterator-method.js",
      "npm:core-js@2.1.0/modules/core.get-iterator.js",
      "npm:core-js@2.1.0/modules/core.is-iterable.js",
      "npm:core-js@2.1.0/modules/core.number.iterator.js",
      "npm:core-js@2.1.0/modules/core.object.classof.js",
      "npm:core-js@2.1.0/modules/core.object.define.js",
      "npm:core-js@2.1.0/modules/core.object.is-object.js",
      "npm:core-js@2.1.0/modules/core.object.make.js",
      "npm:core-js@2.1.0/modules/core.regexp.escape.js",
      "npm:core-js@2.1.0/modules/core.string.escape-html.js",
      "npm:core-js@2.1.0/modules/core.string.unescape-html.js",
      "npm:core-js@2.1.0/modules/es6.array.copy-within.js",
      "npm:core-js@2.1.0/modules/es6.array.every.js",
      "npm:core-js@2.1.0/modules/es6.array.fill.js",
      "npm:core-js@2.1.0/modules/es6.array.filter.js",
      "npm:core-js@2.1.0/modules/es6.array.find-index.js",
      "npm:core-js@2.1.0/modules/es6.array.find.js",
      "npm:core-js@2.1.0/modules/es6.array.for-each.js",
      "npm:core-js@2.1.0/modules/es6.array.from.js",
      "npm:core-js@2.1.0/modules/es6.array.index-of.js",
      "npm:core-js@2.1.0/modules/es6.array.is-array.js",
      "npm:core-js@2.1.0/modules/es6.array.iterator.js",
      "npm:core-js@2.1.0/modules/es6.array.join.js",
      "npm:core-js@2.1.0/modules/es6.array.last-index-of.js",
      "npm:core-js@2.1.0/modules/es6.array.map.js",
      "npm:core-js@2.1.0/modules/es6.array.of.js",
      "npm:core-js@2.1.0/modules/es6.array.reduce-right.js",
      "npm:core-js@2.1.0/modules/es6.array.reduce.js",
      "npm:core-js@2.1.0/modules/es6.array.slice.js",
      "npm:core-js@2.1.0/modules/es6.array.some.js",
      "npm:core-js@2.1.0/modules/es6.array.sort.js",
      "npm:core-js@2.1.0/modules/es6.array.species.js",
      "npm:core-js@2.1.0/modules/es6.date.now.js",
      "npm:core-js@2.1.0/modules/es6.date.to-iso-string.js",
      "npm:core-js@2.1.0/modules/es6.date.to-json.js",
      "npm:core-js@2.1.0/modules/es6.date.to-string.js",
      "npm:core-js@2.1.0/modules/es6.function.bind.js",
      "npm:core-js@2.1.0/modules/es6.function.has-instance.js",
      "npm:core-js@2.1.0/modules/es6.function.name.js",
      "npm:core-js@2.1.0/modules/es6.map.js",
      "npm:core-js@2.1.0/modules/es6.math.acosh.js",
      "npm:core-js@2.1.0/modules/es6.math.asinh.js",
      "npm:core-js@2.1.0/modules/es6.math.atanh.js",
      "npm:core-js@2.1.0/modules/es6.math.cbrt.js",
      "npm:core-js@2.1.0/modules/es6.math.clz32.js",
      "npm:core-js@2.1.0/modules/es6.math.cosh.js",
      "npm:core-js@2.1.0/modules/es6.math.expm1.js",
      "npm:core-js@2.1.0/modules/es6.math.fround.js",
      "npm:core-js@2.1.0/modules/es6.math.hypot.js",
      "npm:core-js@2.1.0/modules/es6.math.imul.js",
      "npm:core-js@2.1.0/modules/es6.math.log10.js",
      "npm:core-js@2.1.0/modules/es6.math.log1p.js",
      "npm:core-js@2.1.0/modules/es6.math.log2.js",
      "npm:core-js@2.1.0/modules/es6.math.sign.js",
      "npm:core-js@2.1.0/modules/es6.math.sinh.js",
      "npm:core-js@2.1.0/modules/es6.math.tanh.js",
      "npm:core-js@2.1.0/modules/es6.math.trunc.js",
      "npm:core-js@2.1.0/modules/es6.number.constructor.js",
      "npm:core-js@2.1.0/modules/es6.number.epsilon.js",
      "npm:core-js@2.1.0/modules/es6.number.is-finite.js",
      "npm:core-js@2.1.0/modules/es6.number.is-integer.js",
      "npm:core-js@2.1.0/modules/es6.number.is-nan.js",
      "npm:core-js@2.1.0/modules/es6.number.is-safe-integer.js",
      "npm:core-js@2.1.0/modules/es6.number.max-safe-integer.js",
      "npm:core-js@2.1.0/modules/es6.number.min-safe-integer.js",
      "npm:core-js@2.1.0/modules/es6.number.parse-float.js",
      "npm:core-js@2.1.0/modules/es6.number.parse-int.js",
      "npm:core-js@2.1.0/modules/es6.number.to-fixed.js",
      "npm:core-js@2.1.0/modules/es6.number.to-precision.js",
      "npm:core-js@2.1.0/modules/es6.object.assign.js",
      "npm:core-js@2.1.0/modules/es6.object.create.js",
      "npm:core-js@2.1.0/modules/es6.object.define-properties.js",
      "npm:core-js@2.1.0/modules/es6.object.define-property.js",
      "npm:core-js@2.1.0/modules/es6.object.freeze.js",
      "npm:core-js@2.1.0/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@2.1.0/modules/es6.object.get-own-property-names.js",
      "npm:core-js@2.1.0/modules/es6.object.get-prototype-of.js",
      "npm:core-js@2.1.0/modules/es6.object.is-extensible.js",
      "npm:core-js@2.1.0/modules/es6.object.is-frozen.js",
      "npm:core-js@2.1.0/modules/es6.object.is-sealed.js",
      "npm:core-js@2.1.0/modules/es6.object.is.js",
      "npm:core-js@2.1.0/modules/es6.object.keys.js",
      "npm:core-js@2.1.0/modules/es6.object.prevent-extensions.js",
      "npm:core-js@2.1.0/modules/es6.object.seal.js",
      "npm:core-js@2.1.0/modules/es6.object.set-prototype-of.js",
      "npm:core-js@2.1.0/modules/es6.object.to-string.js",
      "npm:core-js@2.1.0/modules/es6.parse-float.js",
      "npm:core-js@2.1.0/modules/es6.parse-int.js",
      "npm:core-js@2.1.0/modules/es6.promise.js",
      "npm:core-js@2.1.0/modules/es6.reflect.apply.js",
      "npm:core-js@2.1.0/modules/es6.reflect.construct.js",
      "npm:core-js@2.1.0/modules/es6.reflect.define-property.js",
      "npm:core-js@2.1.0/modules/es6.reflect.delete-property.js",
      "npm:core-js@2.1.0/modules/es6.reflect.enumerate.js",
      "npm:core-js@2.1.0/modules/es6.reflect.get-own-property-descriptor.js",
      "npm:core-js@2.1.0/modules/es6.reflect.get-prototype-of.js",
      "npm:core-js@2.1.0/modules/es6.reflect.get.js",
      "npm:core-js@2.1.0/modules/es6.reflect.has.js",
      "npm:core-js@2.1.0/modules/es6.reflect.is-extensible.js",
      "npm:core-js@2.1.0/modules/es6.reflect.own-keys.js",
      "npm:core-js@2.1.0/modules/es6.reflect.prevent-extensions.js",
      "npm:core-js@2.1.0/modules/es6.reflect.set-prototype-of.js",
      "npm:core-js@2.1.0/modules/es6.reflect.set.js",
      "npm:core-js@2.1.0/modules/es6.regexp.constructor.js",
      "npm:core-js@2.1.0/modules/es6.regexp.flags.js",
      "npm:core-js@2.1.0/modules/es6.regexp.match.js",
      "npm:core-js@2.1.0/modules/es6.regexp.replace.js",
      "npm:core-js@2.1.0/modules/es6.regexp.search.js",
      "npm:core-js@2.1.0/modules/es6.regexp.split.js",
      "npm:core-js@2.1.0/modules/es6.regexp.to-string.js",
      "npm:core-js@2.1.0/modules/es6.set.js",
      "npm:core-js@2.1.0/modules/es6.string.anchor.js",
      "npm:core-js@2.1.0/modules/es6.string.big.js",
      "npm:core-js@2.1.0/modules/es6.string.blink.js",
      "npm:core-js@2.1.0/modules/es6.string.bold.js",
      "npm:core-js@2.1.0/modules/es6.string.code-point-at.js",
      "npm:core-js@2.1.0/modules/es6.string.ends-with.js",
      "npm:core-js@2.1.0/modules/es6.string.fixed.js",
      "npm:core-js@2.1.0/modules/es6.string.fontcolor.js",
      "npm:core-js@2.1.0/modules/es6.string.fontsize.js",
      "npm:core-js@2.1.0/modules/es6.string.from-code-point.js",
      "npm:core-js@2.1.0/modules/es6.string.includes.js",
      "npm:core-js@2.1.0/modules/es6.string.italics.js",
      "npm:core-js@2.1.0/modules/es6.string.iterator.js",
      "npm:core-js@2.1.0/modules/es6.string.link.js",
      "npm:core-js@2.1.0/modules/es6.string.raw.js",
      "npm:core-js@2.1.0/modules/es6.string.repeat.js",
      "npm:core-js@2.1.0/modules/es6.string.small.js",
      "npm:core-js@2.1.0/modules/es6.string.starts-with.js",
      "npm:core-js@2.1.0/modules/es6.string.strike.js",
      "npm:core-js@2.1.0/modules/es6.string.sub.js",
      "npm:core-js@2.1.0/modules/es6.string.sup.js",
      "npm:core-js@2.1.0/modules/es6.string.trim.js",
      "npm:core-js@2.1.0/modules/es6.symbol.js",
      "npm:core-js@2.1.0/modules/es6.typed.array-buffer.js",
      "npm:core-js@2.1.0/modules/es6.typed.data-view.js",
      "npm:core-js@2.1.0/modules/es6.typed.float32-array.js",
      "npm:core-js@2.1.0/modules/es6.typed.float64-array.js",
      "npm:core-js@2.1.0/modules/es6.typed.int16-array.js",
      "npm:core-js@2.1.0/modules/es6.typed.int32-array.js",
      "npm:core-js@2.1.0/modules/es6.typed.int8-array.js",
      "npm:core-js@2.1.0/modules/es6.typed.uint16-array.js",
      "npm:core-js@2.1.0/modules/es6.typed.uint32-array.js",
      "npm:core-js@2.1.0/modules/es6.typed.uint8-array.js",
      "npm:core-js@2.1.0/modules/es6.typed.uint8-clamped-array.js",
      "npm:core-js@2.1.0/modules/es6.weak-map.js",
      "npm:core-js@2.1.0/modules/es6.weak-set.js",
      "npm:core-js@2.1.0/modules/es7.array.includes.js",
      "npm:core-js@2.1.0/modules/es7.error.is-error.js",
      "npm:core-js@2.1.0/modules/es7.map.to-json.js",
      "npm:core-js@2.1.0/modules/es7.math.iaddh.js",
      "npm:core-js@2.1.0/modules/es7.math.imulh.js",
      "npm:core-js@2.1.0/modules/es7.math.isubh.js",
      "npm:core-js@2.1.0/modules/es7.math.umulh.js",
      "npm:core-js@2.1.0/modules/es7.object.entries.js",
      "npm:core-js@2.1.0/modules/es7.object.get-own-property-descriptors.js",
      "npm:core-js@2.1.0/modules/es7.object.values.js",
      "npm:core-js@2.1.0/modules/es7.reflect.define-metadata.js",
      "npm:core-js@2.1.0/modules/es7.reflect.delete-metadata.js",
      "npm:core-js@2.1.0/modules/es7.reflect.get-metadata-keys.js",
      "npm:core-js@2.1.0/modules/es7.reflect.get-metadata.js",
      "npm:core-js@2.1.0/modules/es7.reflect.get-own-metadata-keys.js",
      "npm:core-js@2.1.0/modules/es7.reflect.get-own-metadata.js",
      "npm:core-js@2.1.0/modules/es7.reflect.has-metadata.js",
      "npm:core-js@2.1.0/modules/es7.reflect.has-own-metadata.js",
      "npm:core-js@2.1.0/modules/es7.reflect.metadata.js",
      "npm:core-js@2.1.0/modules/es7.set.to-json.js",
      "npm:core-js@2.1.0/modules/es7.string.at.js",
      "npm:core-js@2.1.0/modules/es7.string.pad-end.js",
      "npm:core-js@2.1.0/modules/es7.string.pad-start.js",
      "npm:core-js@2.1.0/modules/es7.string.trim-left.js",
      "npm:core-js@2.1.0/modules/es7.string.trim-right.js",
      "npm:core-js@2.1.0/modules/es7.system.global.js",
      "npm:core-js@2.1.0/modules/web.dom.iterable.js",
      "npm:core-js@2.1.0/modules/web.immediate.js",
      "npm:core-js@2.1.0/modules/web.timers.js",
      "npm:core-js@2.1.0/shim.js",
      "npm:process@0.11.2.js",
      "npm:process@0.11.2/browser.js",
      "npm:systemjs-plugin-json@0.1.0.js",
      "npm:systemjs-plugin-json@0.1.0/json.js"
    ]
  },

  map: {
    "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.1.2",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.2",
    "aurelia-i18n": "npm:aurelia-i18n@0.4.10",
    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.1.3",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.1.1",
    "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
    "babel": "npm:babel-core@5.8.35",
    "babel-runtime": "npm:babel-runtime@5.8.35",
    "core-js": "npm:core-js@1.2.6",
    "img": "github:systemjs/plugin-image@0.1.0",
    "json": "npm:systemjs-plugin-json@0.1.0",
    "systemjs-plugin-json": "npm:systemjs-plugin-json@0.1.0",
    "systemjs/plugin-image": "github:systemjs/plugin-image@0.1.0",
    "systemjs/plugin-text": "github:systemjs/plugin-text@0.0.4",
    "text": "github:systemjs/plugin-text@0.0.4",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-binding@1.0.0-beta.1.1.3": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1.1.2": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.2",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.1.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.1.2",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.1.2",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.1.3",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.1.1",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.1.1",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-framework@1.0.0-beta.1.1.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1.1.2": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:aurelia-i18n@0.4.10": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.1.1",
      "i18next": "github:i18next/i18next@1.11.2",
      "intl": "npm:intl@1.0.1"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.1.2": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-loader@1.0.0-beta.1.1.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1.1.4": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-metadata@1.0.0-beta.1.1.4": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1.1.3": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1.1.1": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:aurelia-router@1.0.0-beta.1.1.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1.1.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1.1.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.1.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.1.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating@1.0.0-beta.1.1.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.0"
    },
    "npm:babel-runtime@5.8.35": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@2.1.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:intl@1.0.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
