# This file contains the configuration variable used to generate files from
# templates. Copy this file into config/config.dev.toml and config/config.prod.toml. Then
# replace the relevant values.

[api]
host = 'api.arenaoftitans.com'
path = '/ws/{socket_id}'
port = 80
wss_port = 443


[test]
# If debug is set to true, you will directly be taken to the game. You will play as the 1st
# player. The second player will be an AI.
debug = false
