# This file contains the configuration variable used to generate files from
# templates for production. Copy this file into config/config.<type>.toml
# replace the relevant values.
# Available types: dev, testing
# Types that must match the configuration of the server: prod, staging

[api]
host = 'api.arenaoftitans.com'
path = '/ws/{version}'
port = 80
tls_port = 443
